matrix:
    include:
        # - language: python
        #   python: 3.7
        #   before_script:
        #     - cd backend/tests
        #   script:
        #     - python -m unittest discover

      - language: node_js
        before_script:
          - cd ui
