matrix:
    include:
        # - language: python
        #   python: 3.7
        #   before_script:
        #     - cd backend/tests
        #   script:
        #     - python -m unittest discover

      - language: node_js
        node_js: 12
        before_script:
          - cd ui
        script:
          - yarn install
          - yarn test
