language: generic

jobs:
    include:
      - language: python
        python: 3.7
        install:
          - pip install -r requirements.txt
          - python setup.py develop
        script:
          - cd servian_twitter
          - pytest -v -m "not index_test"

      - language: node_js
        node_js: 13
        cache: yarn
        script:
          - cd ui
          - yarn install
          - yarn test
