language: generic

jobs:
    include:
      - stage: "Compile and test python backend"
      - language: python
        python: 3.7
        install:
          - pip install -r requirements.txt
          - python setup.py develop
        script:
          - cd servian_twitter
          - pytest -v -m "not index_test"

      - stage: deploy
        name: "Compile and test UI, then deploy to Google App Engine"
      - language: node_js
        node_js: 13
        cache: yarn
        script:
          - cd ui
          - yarn install
          - yarn test
          - cd ../

        before_deploy:
        - bash build_ui.sh # Build the UI module. Must be done in deploy stage, because we generate the index.html file
        - openssl aes-256-cbc -K $encrypted_645f850629f0_key -iv $encrypted_645f850629f0_iv
          -in hazel-tome-269200-2c4a7c4121d6.json.enc -out hazel-tome-269200-2c4a7c4121d6.json
          -d

        deploy:
            provider: gae
            keyfile: "hazel-tome-269200-2c4a7c4121d6.json"
            project: "hazel-tome-269200"
